apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  appsettings.json: |-
    {
      "Routes": [   
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/account/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/account/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/abp/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/abp/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Catalog Service",
      "DownstreamPathTemplate": "/api/catalog/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.catalogService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.catalogService.host }}",
          "Port": "{{ .Values.reRoutes.catalogService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/catalog/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Basket Service",
      "DownstreamPathTemplate": "/api/basket/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.basketService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.basketService.host }}",
          "Port": "{{ .Values.reRoutes.basketService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/basket/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Ordering Service",
      "DownstreamPathTemplate": "/api/ordering/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.orderService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.orderService.host }}",
          "Port": "{{ .Values.reRoutes.orderService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/ordering/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    }]
    }