apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  ocelot.json: |-
    {
      "GlobalConfiguration": {
      "BaseUrl": "{{ .Values.config.globalConfigurationBaseUrl }}"
    },
      "Routes": [   
    {
      "ServiceKey": "Account Service",
      "DownstreamPathTemplate": "/api/account/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.accountService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.accountService.host }}",
          "Port": {{ .Values.reRoutes.accountService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/account/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/abp/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/abp/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Catalog Service",
      "DownstreamPathTemplate": "/api/catalog/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.catalogService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.catalogService.host }}",
          "Port": "{{ .Values.reRoutes.catalogService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/c/catalog/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Basket Service",
      "DownstreamPathTemplate": "/api/basket/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.basketService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.basketService.host }}",
          "Port": "{{ .Values.reRoutes.basketService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/basket/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Ordering Service",
      "DownstreamPathTemplate": "/api/ordering/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.orderingService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.orderingService.host }}",
          "Port": "{{ .Values.reRoutes.orderingService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/ordering/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    }]
    }