version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks: 
      - eshoponabp-network

  mongodb:
    container_name: mongodb
    image: mongo:4.2
    volumes:
       - mongodb_data:/data/db
    networks: 
      - eshoponabp-network  
  redis:
    container_name: redis
    image: redis:alpine
    networks: 
      - eshoponabp-network
    
  postgres-db:
    container_name: postgres-db
    image: postgres:14.1
    volumes:
      - postgres_data:/var/opt/postgres
    networks: 
      - eshoponabp-network
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.2    
    volumes:
       - pgadmin_data:/var/lib/pgadmin
    networks: 
      - eshoponabp-network   

volumes:
  postgres_data:
  pgadmin_data:
  mongodb_data:

networks:
  eshoponabp-network:
    external: true