# auth-server sub-chart override
authserver:
  config:
    selfUrl: https://eshop-st-authserver    
    corsOrigins: https://eshop-st-gateway-web,https://eshop-st-gateway-web-public,https://eshop-st-gateway-internal
    allowedRedirectUrls: https://eshop-st-web
    connectionStrings:
      administrationService: "Host=es-st-postgresdb;Port=5432;Database=EShopOnAbp_Administration;User ID=postgres;password=myPassw0rd;Pooling=false"
      identityService: "Host=es-st-postgresdb;Port=5432;Database=EShopOnAbp_Identity;User ID=postgres;password=myPassw0rd;Pooling=false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch
  ingress:
    host: eshop-st-authserver
  image:
    repository: "eshoponabp/app-authserver"
    tag: latest

# web sub-chart override
web:
  config:
    selfUrl: https://eshop-st-web
    gatewayUrl: "https://eshop-st-gateway-web/"
  ingress:
    host: eshop-st-web
  image:
    repository: "eshoponabp/app-web"
    tag: latest

# public-web sub-chart override
public-web:
  config:
    selfUrl: https://eshop-st-public-web
    gatewayUrl: "http://eshop-st-gateway-web-public/"
    authServer:
      authority: http://eshop-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch
  ingress:
    host: eshop-st-public-web
  image:
    repository: "eshoponabp/app-publicweb"
    tag: latest

# identity-service sub-chart override
identity:
  config:
    selfUrl: https://eshop-st-identity
    corsOrigins: https://eshop-st-gateway-web,https://eshop-st-gateway-web-public
    connectionStrings:
      identityService: "Host=es-st-postgresdb;Port=5432;Database=EShopOnAbp_Identity;User ID=postgres;password=myPassw0rd;Pooling=false"
      administrationService: "Host=es-st-postgresdb;Port=5432;Database=EShopOnAbp_Administration;User ID=postgres;password=myPassw0rd;Pooling=false"
    authServer:
      authority: http://eshop-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch    
  identityServerClients: # Seeded Clients
    webRootUrl: https://eshop-st-web/  
    publicWebRootUrl: https://eshop-st-public-web/
    webGatewayRootUrl: https://eshop-st-gateway-web/
    publicWebGatewayRootUrl: https://eshop-st-gateway-web-public/
    identityServiceRootUrl: https://eshop-st-identity/
    administrationServiceRootUrl: https://eshop-st-administration/
  ingress:
    host: eshop-st-identity
  image:
    repository: "eshoponabp/service-identity"
    tag: latest

# administration sub-chart override
administration:
  config:
    selfUrl: https://eshop-st-administration
    gatewayUrl: https://eshop-st-gateway-internal/
    corsOrigins: https://eshop-st-gateway-web,https://eshop-st-gateway-web-public,https://eshop-st-gateway-internal
    connectionStrings:
      administrationService: "Host=es-st-postgresdb;Port=5432;Database=EShopOnAbp_Administration;User ID=postgres;password=myPassw0rd;Pooling=false"
    authServer:
      authority: http://eshop-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch
  synchedCommunication: # Used for server-to-server (client-credentials) communication with identityService for user permissions
    authority: https://eshop-st-authserver
  ingress:
    host: eshop-st-administration
  image:
    repository: "eshoponabp/service-administration"
    tag: latest

# gateway-web sub-chart override
gateway-web:
  config:
    selfUrl: https://eshop-st-gateway-web
    corsOrigins: https://eshop-st-web
    globalConfigurationBaseUrl: http://eshop-st-gateway-public
    authServer:
      authority: http://eshop-st-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch
    stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  ingress:
    host: eshop-st-gateway-web
  image:
    repository: "eshoponabp/gateway-web"
    tag: latest
  reRoutes:
    identityService:
      schema: http
      host: eshop-st-identity
      port: 80
    administrationService:
      schema: http
      host: eshop-st-administration
      port: 80

# gateway-web-public sub-chart override
gateway-web-public:
  config:
    selfUrl: https://eshop-st-gateway-web-public
    globalConfigurationBaseUrl: http://eshop-st-gateway-public-web
    authServer:
      authority: http://eshop-st-AUTHSERVER
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: es-st-redis
    rabbitmqHost: es-st-rabbitmq
    elasticsearchHost: es-st-elasticsearch
    stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  ingress:
    host: eshop-st-gateway-web-public
  image:
    repository: "eshoponabp/gateway-web-public"
    tag: latest
  reRoutes:
    identityService:
      schema: http
      host: eshop-st-identity
      port: 80
    administrationService:
      schema: http
      host: eshop-st-administration
      port: 80
    catalogService:
      schema: http
      host: eshop-st-catalog
      port: 80
    basketService:
      schema: http
      host: eshop-st-basket
      port: 80
    orderService:
      schema: http
      host: eshop-st-order
      port: 80


# Default values for eshoponabp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}