config:
  selfUrl: https://eshop-st-public-web
  gatewayUrl: https://eshop-st-gateway-web-public
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
  dotnetEnv: Staging
  redisHost: es-st-redis
  rabbitmqHost: es-st-rabbitmq
  elasticsearchHost: es-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: eshop-st-public-web
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}
