config:
  selfUrl: # https://eshop-st-gateway-web
  corsOrigins: # localhost:4200
  globalConfigurationBaseUrl: # http://eshop-st-gateway-web
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"  
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchHost: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
reRoutes:
  identityService:
    schema: http
    host: eshop-st-identity
    port: 80
  administrationService:
    schema: http
    host: eshop-st-administration
    port: 80
ingress:
  host: # eshop-st-gateway-web
  tlsSecret: eshop-demo-tls

image:
  repository: eshoponabp/gateway-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}